### ISSUE TITLE
Missing realms from population graphs

### ISSUE THREAD

**Issue by ReidWeb** [XIVStats/XIVStats#14]
As highlighted by a user on Reddit, there was a realm missing from the output.

I've checked through them all

## American Realms (Aether & Primal Datacentres)

- None missing

## Japanese Realms (Mana, Gaia and Elemental Datacentres)
- Atomos - typo in script - it is accidentally spelt 'Atomis'

## EU Realms

- None missing

Seems our graphing UI framework removes elements with 0 value. The SQL query would have returned 0 with this typo in place.

**Comment by ReidWeb** [comment]
CC: @Bwin4L

**Comment by ReidWeb** [comment]
@Pricetx was this resolved?

**Comment by Pricetx** [comment]
This is resolved.
