### ISSUE TITLE
June 2017 DB link is broken

### ISSUE THREAD

**Issue by Bwin4L** [XIVStats/XIVStats#16]
The link at the bottom of the page (https://ffxivcensus.com/2017-06/ffxivcensus-2017-06.zip) points to a non existent resource

**Comment by Pricetx** [comment]
Hello. June had been manually run, and in the process of doing so I had typo'd the filename. The name has now been fixed and the link works. July onwards will be back to the automated setup so this shouldn't happen in future.

**Comment by Bwin4L** [comment]
Okay, thanks a lot!
