### ISSUE TITLE
Add Red Mage and Samurai to webpage

### ISSUE THREAD

**Issue by ReidWeb** [XIVStats/XIVStats#17]
Add Red Mage and Samurai data to web page.

Requires completion of XIVStats-Gatherer-Java/issues#21.

**Comment by Pricetx** [comment]
The required code for these new classes has been added. There is a test run currently in progress. I will be able to verify this within a day or two.

**Comment by Balls0fSteel** [comment]
Started my own page (was investigating something), and it looks like the new code works fine: http://ffstat.agx.co/

**Comment by Pricetx** [comment]
Thanks for running a test.

I can now confirm that our test run of 1 million IDs came back successfully (https://dev.ffxivcensus.com/).

I will prepare the next live run to commence on the 1st of September.
