### ISSUE TITLE
Changes to Veteran Rewards in 4.1 

### ISSUE THREAD

**Issue by crakila** [XIVStats/XIVStats#26]
(I know I have already mentioned this to @Pricetx and @ReidWeb but I felt I should create an issue here)

In 4.1 (Releasing October 10th), Square-Enix is going to be changing the Veteran Reward system.
Details here: http://na.finalfantasyxiv.com/lodestone/topics/detail/ca42d41cbd6e7849ba92978235f0d5dc926e72db

All (but a couple of items) are being removed from the Veteran Rewards and moved to Jonathas in Old Gridania for pickup using "achievement certificates"

The changes are as follows:

Advent Attire (Cloud Strife)
WAS: Rank 10 - 720 days
NOW: Rank 1 - 60 days

Tantalus Attire (Zidane)
WAS: Rank 13 - 1080 days
NOW: Rank 2 - 150 days

Wild Rose Attire (Kain ?)
WAS: Rank 11 - 840 Days
NOW: Rank 3 - 240 days.

Leonhart Attire (Squall Leonhart)
WAS: Rank 14 - 1440 days
NOW: Rank 4 - 330 days.

So it looks like that some adjustments may be needed going forward

**Comment by Pricetx** [comment]
This poses a problem for the "subscribed time" chart on the site, as the result will be a combination of people with the previous achievements and people with the revised achievements.

I think the data should be kept as-is, but with a note on potential inaccuracy and a link to the lodestone topic. This is preferable over losing the statistics altogether.

This may be reviewed again in future as theoretically over time the statistics will become progressively less sound.
