### ISSUE TITLE
Change active check to look for Yol from 4.0 story instead of minion from 3.3

### ISSUE THREAD

**Issue by Pricetx** [XIVStats/XIVStats#28]
Patch 3.3 was now over a year ago so it doesn't make much sense to keep using it for the active check.

Until the day when a better system of determining active players is around, this should be updated to look for the "Yol" mount, which is obtained during the 4.0 story. This is not captured as an individual data point at the moment, but is part of the list of mounts that gets captured.

**Comment by Pricetx** [comment]
@matthewhillier It would be great if you were able to look at this, as you're the person most familiar with the optimisation work previously carried out. It may be that we can extract it from the list of mounts fairly efficiently, or failing that it may be that a new column gets created in the gatherer to record this mount specifically. Let me know what you think!

**Comment by matthewhillier** [comment]
Done. See Pull Request #29.

The numbers are pretty sad with this check. :(
