### ISSUE TITLE
Add bars to levels/classes graphs to show level 50s

### ISSUE THREAD

**Issue by ReidWeb** [XIVStats/XIVStats#3]
Add a second bar (colour it differently) to show the level 50 characters along side the level 60s.

Also possibly add a 'all' bar.

Or you can use a stacked bar graph for this.

**Comment by AdriaanDeVos** [comment]
This would louk perfect in a stacked bar graph.

**Comment by Pricetx** [comment]
This suggestion isn't really relevant any longer.
