### ISSUE TITLE
Errors when running XIVStats against the latest Java gatherer

### ISSUE THREAD

**Issue by Pricetx** [XIVStats/XIVStats#31]
The following errors occur when running XIVStats against a database generated by the latest Java Gatherer from the unattended_gathering branch;

PHP Notice:  Undefined index: female in xiv_stats.php on line 1016
PHP Notice:  Undefined index: male in xiv_stats.php on line 1025

The current results of a run can be seen here: http://dev.ffxivcensus.com

The run was a limited size one, so ignore the overall numbers being low. Specially, there appears to be an issue with the chart output.

**Comment by matthewhillier** [comment]
Hey @Pricetx,

Opened a new Pull Request #32 to address issue. There were some scenarios where running the PHP against a small DB snapshot meant that some of the individual stats returned `nil` and thus killed the Javascript.

Also, just a note on the new gatherer, suggest using the branch for #30, as this filters out the deleted characters that the gatherer now tracks.

Cheers

**Comment by Pricetx** [comment]
I have re-run it against the new branch.

It certainly works much better. The grand company distribution is a little off, but I think that's because it didn't pull in one of the race names properly. This is more likely due to the small run than a fault in the PHP.

I'll approve the pull request.
