### ISSUE TITLE
Mounts and Minions columns missing from ffxivcensus.tblplayers?

### ISSUE THREAD

**Issue by Bwin4L** [XIVStats/XIVStats#35]
I might have missed something, but the mounts and minions columns seem to have completely vanished from the tblplayers table. Is this expected? I was using these fields to filter bots.
Note: I did not import anything into my local DBMS since July's census, so I can only say it was working in June and not anymore in October.

**Comment by matthewhillier** [comment]
Interesting... they're still in the schema, but don't show up in the dump. Could be that they're being excluded to save space, as they were optional at one point.

**Comment by ReidWeb** [comment]
@Pricetx would be able to comment - not actively involved in the gathering node RN.

**Comment by Pricetx** [comment]
This is a known issue, and is linked to the active figure on the website being 0. The live site is running a version of the gatherer from where mounts were optional, but it not configured with the correct flag. Work is underway to update the live site to the latest version of the gatherer and is currently reliant on this issue being resolved: https://github.com/XIVStats/XIVStats-Gatherer-Java/issues/37

**Comment by Pricetx** [comment]
This should be resolved once the re-run of the February census completes. Note to self to confirm this.

**Comment by Pricetx** [comment]
I have confirmed that this is now working as of the latest census.
