### ISSUE TITLE
Missing charts

### ISSUE THREAD

**Issue by ngld** [XIVStats/XIVStats#36]
The charts rendered after "race and gender distribution" are missing and the chart itself is empty.

Looks like this is caused to to invalid data being passed to highcharts. The relevant code looks like this right now:
```javascript
              series: [{
                  name: 'Female',
                  data: [
                      3672,3358,10229,8277,22122,,990,                  ],
              }, {
                  name: 'Male',
                  data: [
                      1736,6035,14764,11359,6404,,4363,                  ],
              }]
```

There's a double comma in there (I assume that's due to the value there being 0) which produces an exception deep in highcharts. Apparently Chromium interprets this as a `null` value and highcharts ends up trying to access a property on that which causes an exception to be thrown since you can't access properties on a `null` value.
The exception then halts JavaScript execution which is why the other graphs are affected as well.

From a quick glance, it looks like the code should be handling this problem correctly. The only suggestion I can make would be replacing the the `isset($value)` check in `getValue` with `!empty($value)`.

**Comment by matthewhillier** [comment]
@Pricetx - Did you try re-running the gatherer? The Dec stats look like they gave up not long after starting?

**Comment by Pricetx** [comment]
This issue is no longer present in testing. The current latest census has missing charts due to bug #36 on the Java Gatherer. This has now been resolved and all charts should be present before the end of the month.

Thanks for highlighting this.
