### ISSUE TITLE
Fix Qitari beast tribe reward 

### ISSUE THREAD

**Issue by ReidWeb** [XIVStats/XIVStats#62]
The qitari beast tribe reward is showing as 0. Look into why and apply fix.

Should just require a re-run of the PHP, so a census re-run is not required

**Comment by crakila** [comment]
Commit https://github.com/XIVStats/XIVStats/commit/ff88575295a59480a6d7b62eed8104a4cfc7285b fixes this as it was not checking for the Qitari beast tribe mount. 

Why it didn't pick up on the minion is something I will need to investigate. The mount should be fine for this.

**Comment by crakila** [comment]
Locally, I tested this by removing the mount check for this and leaving the minion checks and it does work:

```
$beast_tribes["Qitari"] += in_array("The Behelmeted Serpent of Ronka", $minions) || in_array("The Behatted Serpent of Ronka", $minions) ? 1 : 0;
```

but on the live site it is not working. 

@Pricetx Was there any errors from the php whenever it was being run?

**Comment by crakila** [comment]
It seems that as of the new census for April 2022, this has not been fixed on live. We'll need to check this again....

**Comment by crakila** [comment]
This has been resolved and is live on the dev site - https://s3.eu-west-2.amazonaws.com/dev.ffxivcensus.com/index.html
Will be live on the website on next census run.
