### ISSUE TITLE
Fix copy for eternal bonds

### ISSUE THREAD

**Issue by ReidWeb** [XIVStats/XIVStats#63]
The eternal bond stats relate to items only issued for certain tiers of eternal bond: 

Quoting a community member:
"guest at an eternal bond is only given to the gold and platinum eternal bonds, need to update the copy on that later".

Can maybe just put 'a gold/silver' eternal bond in there? Thoughts?

**Comment by crakila** [comment]
1. 
![image](https://user-images.githubusercontent.com/405804/154335077-23a2dd05-5575-4cea-979c-4dbee2e4f645.png)

2.
![image](https://user-images.githubusercontent.com/405804/154335212-72482662-03cc-4e8b-8c96-b95c60d8268e.png)

I like 1 more but I'll leave it up to you. e personally but what do you think?

**Comment by ReidWeb** [comment]
I like 1, how does it look like alongside the adjacent elements? I'd wonder if adding the additional subtitle will 'push' elements beneath this down further than the neigbouring elements if you get me? i.e. grid wouldn't line up?

**Comment by crakila** [comment]
It doesn't affect the elements below in terms of the positioning

![image](https://user-images.githubusercontent.com/405804/154338214-c4bd03d9-c5b6-4154-94b1-847a1f698706.png)

**Comment by ReidWeb** [comment]
Shifts alignment of the number with the adjacent element to the right though? Though I suppose that's getting updated copy too?

**Comment by ReidWeb** [comment]
looks good with that then. [Apparently it should read as Gold & Platinum rather than Silver & Gold](https://www.finalfantasyxiv.com/eternalbond/eu/detail/overview.html)

As regards the copy for the second item, it's ceremony chocobo we use, so it's Gold & Platinum too
