### ISSUE TITLE
Evaluate issues with census mis-reporting data in 2017-03-16 test-run

### ISSUE THREAD

**Issue by ReidWeb** [XIVStats/XIVStats#7]
_Initially discussed in #1_

For the test run of v1.3.0 of the gatherer program that was completed 2017-03-15, and the output of the XIVStats script run through to [2017-03-16](https://ffxivcensus.com/2017-03/) the statistics are extremely diminished on the figures for the beginning of [February](https://ffxivcensus.com/2017-02/).

Taking some samples from the page:

| Metric | February | Test Run |
|--------|----------|-------|
| World Players | 10.1 million | 8.1 million |
| Eternal Bond Guest | 319k | 259k |
| Eternal Bond Married | 121k | 99k |
| ARR Soundtrack | 76k | 57k |

From this small sample of metrics and comparing the two sites side by side, you can see that the results are obviously affected by some sort of issue.

# Suggested Incident Response

- [x] @Pricetx - revert page for 2017-03 to the data from 2017-03-04, and restore the index page symlink.

- [x] @Pricetx - Investigate cause of issue with data being misreported, ascertain as to whether it was a network or system issue

- [x] @Pricetx / @ReidWeb - load a dump of the database from 2017-03-04 in once restored, and do a compare of the 'missing' data between the 2017-03-04 and 2017-03-16. Find missing IDs and manually check out and parse those pages - to ensure they still exist - it might be that they actually got deleted from the lodestone/characters deleted - but that's unlikely in such a large volume?

- [x] @Pricetx / @ReidWeb - verify that the highest player ID for 2017-03-16 was higher than that for 2017-03-04.

# Possible Causes

Listed in my evaluation of most to least likely.

1.  Lodestone was rate limiting us - due to increased connections from 'image date parsing' - we were hitting this when we didn't hit it before
1. Server firewall/network experienced issues that caused requests to not reach the lodestone.

**Comment by ReidWeb** [comment]
When comparing between the databases, numerous characters are missing compared to the start of the month, including character id `1`. I've manually verified and this character is still on lodestone.

**Comment by ReidWeb** [comment]
Max ID for `2017-03-04` is: `16,999,999`
Max ID for `2017-03-16` is: `17,163,987`

**Comment by Pricetx** [comment]
After adding debug code, we have determined that above a certain rate of connections, we are received HTTP response 429 for requests, which is "Too Many Requests". It appears we are being rate limited by the Lodestone. Will investigate possible solutions to ensure that characters do not get skipped.

**Comment by ReidWeb** [comment]
Just implemented a mechanism that evaluates if the status code ist`429` and will 'wait' and 'rerun' until it gets the player! Price is testing this out now with a run - from my local testing on my Mac it doesn't drop any players. Test in a dev environment will provide us with a better image.

**Comment by ReidWeb** [comment]
Initial runs in non-production environment are proving very promising  - not any characters dropped. 🎉

**Comment by ReidWeb** [comment]
Our tests are now indicating we have now found a fix for this issue - @Pricetx will be starting a full run shortly.
