### ISSUE TITLE
Dynamis data centre missing 

### ISSUE THREAD

**Issue by HammerBag** [XIVStats/XIVStats#88]
Your census data is missing the 4 US servers that exist on the Dynamis Logical Datacenter:
-Halicarnassus
-Maduin
-Marilith
-Seraph

**Comment by Crakila** [comment]
Hi there. 

Apologies for the delay in getting back to you, we have been AFK from this project for a _while_.
This is already in as part of #81, but it hasn't been made live on the website. 

It is listed in the `master` branch here https://github.com/XIVStats/XIVStats/blob/master/xiv_stats.php#L97
