### ISSUE TITLE
PvP data on ffxivcensus shows 0 instances of WIN 200 'FEAST' OR 'CRYSTALLINE CONFLICT' MATCHES

### ISSUE THREAD

**Issue by mkosler** [XIVStats/XIVStats#89]
I don't know the exact methodology you all use to parse out this data, but there's very little chance that not a single person has completed this achievement. Comparing against a similar site, ffxivcollect.com, it shows at least 15000 characters own the associated mount, the Gloria-class Airship:

![image](https://github.com/XIVStats/XIVStats/assets/1159095/84e4cb60-1780-4b71-b452-25e66f247f80)

When looking at ffxivcensus.com, the linked item on the header is to the Wind-Up Hildibrand, which is the quest reward for completing the ARR questline:

![image](https://github.com/XIVStats/XIVStats/assets/1159095/33de31ca-8d20-441b-ad22-b6771c889e54)

**Comment by Crakila** [comment]
Hi!

Thanks for reporting this. 
It is still incorrect from the 6.4 changes which I made in #85 

I will be carrying out a big update to add 6.45+ soon™️and I will fix it then.
